name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - run: sudo apt install -y bats
    - uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - run: just test
